name: currency_selector
description: A ready-to-use currency picker dialog with world currencies, symbols and flags.
version: 1.0.1
homepage: https://github.com/JuanGiannattasio/currency_selector
repository: https://github.com/JuanGiannattasio/currency_selector

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
